version: "3.8"
services:
  postgres:
    container_name: postgres_commit.io
    image: bitnami/postgresql:latest
    ports:
      - 5432:${PG_DATABASE_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER= ${PG_DATABASE_USERNAME}
      - POSTGRES_PASSWORD= ${PG_DATABASE_PASSWORD}
      - POSTGRES_DB= ${PG_DATABASE_NAME}
    volumes:
      - ./data/pg:/data/postgres

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:${RABBITMQ_ADMIN_PORT}
      - 5672:${RABBITMQ_PORT}
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
